### ISSUE TITLE
500 server error when using the svg api

### ISSUE THREAD

**Issue by Cankar001** [one-tab-group/bookmark.style#10]
I am trying to use the SVG api for my github readme, but if I replace the link of your demo `https://svg.bookmark.style/api?url=https://bookmark.style/&mode=light&style=horizontal` with my link `https://svg.bookmark.style/api?url=https://cankarka.com/&mode=light&style=horizontal` I am getting the attached error.

![Screenshot](https://user-images.githubusercontent.com/53074877/195984603-2983e649-269a-47ed-beaf-bdec7301a775.png)

**Comment by xiaoluoboding** [comment]
some as #9
