### ISSUE TITLE
npm 包支持

### ISSUE THREAD

**Issue by markthree** [one-tab-group/bookmark.style#3]
也许这个可以成为一个非常好用的 `npm` 包 😂

**Comment by xiaoluoboding** [comment]
参见 [Concepts](https://github.com/one-tab-group/bookmark.style#concepts)

本身 bookmark.style 是依赖自己搭建的 [metafy](https://github.com/one-tab-group/metafy) Serverless function 的

而 [metafy](https://github.com/one-tab-group/metafy) 依赖的就是你所说的 NPM 包
