### ISSUE TITLE
support bookmarklet?

### ISSUE THREAD

**Issue by jiacai2050** [one-tab-group/bookmark.style#4]
```
javascript:window.location=%22http://news.ycombinator.com/submitlink?u=%22+encodeURIComponent(document.location)+%22&t=%22+encodeURIComponent(document.title)
```
This is a bookmarklet for submit post to Hacker News, I hope bookmark.style could add this kinds of support.

**Comment by xiaoluoboding** [comment]
In fact, this feature has already been implemented.

You can create a new bookmarklet, and enter the url like:

```js
javascript:window.location="https://www.bookmark.style/?url="+encodeURIComponent(document.location)
```

I will design the feature drop&drop the bookmarklet into the bookmark bar as Hacker News does.
