### ISSUE TITLE
Can I embed generated bookmark image in GitHub README?

### ISSUE THREAD

**Issue by kaichii** [one-tab-group/bookmark.style#5]
Beautiful bookmark generator! nice work! By the way, Can I use it in GitHub README by image link, for example:

```markdown
![bookmark](https://bookmark.style/?url=<url>&<other options>)
```

**Comment by xiaoluoboding** [comment]
@kaichii That's a new feature, and we need to provide a server to render the image.  Maybe support this feature in the future, but not now.

**Comment by kaichii** [comment]
> @kaichii That's a new feature, and we need to provide a server to render the image. Maybe support this feature in the feature, but not now.

thx! I'm glad to help if needed.

**Comment by xiaoluoboding** [comment]
Sorry to keep you waiting, Finally I creating a service for this feature.

```markdown
https://svg.bookmark.style/api?url=https://bookmark.style&mode=light
```

Now, we can embed the bookmark card in the README.md using this servcie.

```markdown
[![onetab.group](https://svg.bookmark.style/api?url=https://onetab.group&mode=light)](https://onetab.group)
```

Take a look at the service repo: https://github.com/xiaoluoboding/metafy-svg for more details.

have fun.

**Comment by kaichii** [comment]
@xiaoluoboding Nice work!
