### ISSUE TITLE
notion的文章无法识别标题

### ISSUE THREAD

**Issue by welkinbai** [one-tab-group/bookmark.style#7]
![image](https://user-images.githubusercontent.com/13196370/175475725-67ee962a-4682-49fd-9a48-efb78e029454.png)
把notion的一篇文章粘贴进去，没有识别出来文章的标题，展示的是notion的介绍。  
原文链接：https://welkinbai.notion.site/web3-910dd224c6be4b68896397f495acf626

**Comment by xiaoluoboding** [comment]
说明 Notion 很聪明，没有给分享的文章做 SEO，而是给自家站点做 SEO，宣传自己的东西。

**Comment by welkinbai** [comment]
> 说明 Notion 很聪明，没有给分享的文章做 SEO，而是给自家站点做 SEO，宣传自己的东西。

啊，没有解法吗？
