### ISSUE TITLE
URL parser for the logo is not working

### ISSUE THREAD

**Issue by Cankar001** [one-tab-group/bookmark.style#9]
All my websites are not working with this tool, because the URL parser does not work correctly.
It leaves the language prefix in the URL, which leads to a 404 error.

In this screenshot you can see the parsed URL by the tool: 
![Screenshot](https://user-images.githubusercontent.com/53074877/195984253-d4e3b233-17ea-4c4c-9a9a-ebee39acf683.png)

The parsed URL is `https://www.cankarka.com/en/assets/frontend/img/logo.png`, but it should be `https://www.cankarka.com/assets/frontend/img/logo.png`

It would be great if you could fix this issue, other than that the tool works great and the styling looks really awesome!
Thanks for your work! :)

**Comment by xiaoluoboding** [comment]
some as #1
